### ISSUE TITLE
SQL parsing error for update statement

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#128]
## Does not work as expected

```sql
siocli> update test_db set col1 = 'val1' and col2 = 'val2' and col3 = 1 where trid = 1;

Status 2075: UPDATE SET expression is invalid: Logical AND operator: left operand type isn't boolean
```
## Does work as not expected

when using `and` instead of `,` in update command with `null`, `true` or `false`  the command is accepted which is wrong.
Plus the data are not updated properly. This command should be accepted by the parser:

```sql
siocli> update test_db set col1 = null and col2 = null and col3 = 2 where trid = 1;

1 rows affected

siocli> select * from test_db ;
TRID                COL1                                     COL2                                     COL3
------------------- ---------------------------------------- ---------------------------------------- -----------
                  1 NULL                                     val2updated                                        2
```

**Comment by cxxman** [comment]
UPDATE syntax requires field assignments to be separated by comma, so `AND` cannot be used here.
[PostgreSQL](https://www.postgresql.org/docs/9.1/sql-update.html)
[MySQL](https://dev.mysql.com/doc/refman/8.0/en/update.html)
[Oracle](https://docs.oracle.com/cd/B19306_01/appdev.102/b14261/update_statement.htm)
So it works out first statement correctly in terms it generated some error.
So the real problem is why second statement does not produce an error.

**Comment by cxxman** [comment]
What is parse tree for the second statement? (can be taken from the iomgr log in the debug build)

**Comment by niolap** [comment]
@cxxman actually after understanding the concept of expression, it is correct that `update d.t2 set c1 = 'a' and c2 = 1 where trid = 1 ;`  raise the error `Status 2075: UPDATE SET expression is invalid: Logical AND operator: left operand type isn't boolean`. If I change it to a correct expression `update d.t2 set c1 = true and c2 = 1 where trid = 1 ;` then there is no error and the column C1 is updated correctly. 

Thus I think that there is no issue.

**Comment by cxxman** [comment]
So the second one is likely evaluated as follows:
```sql
col1 = (null and col2 = null and col3 = 2)
```
Since operation `AND` with `null` argument results  `null`, therefore the whole expression is like `col1 = null`. That's what you get, and there's also likely no error.

If you agree with this, please close the issue related PR #151, otherwise let's continue discussion.
