### ISSUE TITLE
Instance name missing in dump file

### ISSUE THREAD

**Issue by niolap** [siodb/siodb#72]
The instance name doesn't appear in the header of the dump file:

```
$ siocli --user root --export-all | head -8
-- Siodb SQL dump
-- Hostname: localhost
-- Instance:
-- Timestamp: 2020.07.04 17:56:59
```

**Comment by cxxman** [comment]
@niolap `siocli` (and any other client too) now doesn't know things like instance name, server version, etc. So this requires some changes in the Siodb client protocol. Siodb server has to send server information as first message in the communication with client. You will have to update drivers accordingly. I think this is ok, since we will have multiple changes of the protocol later on, for the things like query cancellation and prepared statements. I am going to make this change during the next week.

**Comment by cxxman** [comment]
we can add instance name to the successful authentication confirmation message

**Comment by niolap** [comment]
@cxxman "add instance name to the successful authentication confirmation message" has significant consequences with a small benefit.
Instead, I think we should have a memory table `mem_instances` that has columns `uuid`, `name` and `hostname`. Then client and export will be able to query that table to get metadata from the instance and we keep the current protocol "as is". Don't you think? But if we choose that method, then it's not a bug and should be shifted for the next epic.

**Comment by cxxman** [comment]
too complicated for now. instance name can be sent as "freetext_message", so no change in protocol messages required.

**Comment by niolap** [comment]
I got it (I thought it was a protocol change). Ok, let's do this to move ahead.

**Comment by cxxman** [comment]
@niolap Please re-test

**Comment by niolap** [comment]
@cxxman works as expected:
$ /home/siodb/siodb/build/release/bin/siocli -a siodb -u root -i /home/siodb/siodb/tests/share/private_key -E
-- Siodb SQL Dump
-- Hostname: localhost
-- Instance: siodb
-- Timestamp: 2020-11-17 19:17:14
-- Timestamp (UTC): 2020-11-17 19:17:14
